import Link from "next/link";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import { ArrowLeft, Shield } from "lucide-react";

export default function PrivacyPage() {
  const sections = [
    {
      title: "Information We Collect",
      content: `When you create an account with NoSnore, we collect the following information:
      
• **Account Information:** Your name, email address, and profile picture, provided via your authentication provider (Clerk).
• **Service Data:** The URLs and names of the endpoints you register for monitoring.
• **Usage Data:** Ping logs, uptime statistics, and service health data generated by our monitoring workers.
• **Payment Information:** Billing details are processed securely by Razorpay. We do not store your card information on our servers.`,
    },
    {
      title: "How We Use Your Information",
      content: `We use the information we collect to:

• Provide, operate, and maintain the NoSnore monitoring service.
• Send HTTP pings to your registered endpoints at your configured intervals.
• Process payments and manage your subscription plan.
• Send you service-related notifications and alerts (if applicable).
• Improve and develop new features for the platform.
• Comply with legal obligations.`,
    },
    {
      title: "Data Sharing and Disclosure",
      content: `We do not sell, trade, or rent your personal information to third parties. We may share data in the following limited circumstances:

• **Service Providers:** We use trusted third-party providers (Clerk for authentication, Convex for the database, Razorpay for payments) who are contractually obligated to protect your data.
• **Legal Requirements:** We may disclose information if required by law, court order, or government authority.
• **Business Transfers:** In the event of a merger or acquisition, your data may be transferred as part of the transaction.`,
    },
    {
      title: "Data Security",
      content: `We take the security of your data seriously. NoSnore implements industry-standard security measures including:

• Encrypted connections (HTTPS/TLS) for all data in transit.
• Secure, managed database infrastructure via Convex.
• Authentication handled by Clerk, a trusted identity provider.
• Access controls that limit who can view your data within our systems.

However, no method of transmission over the Internet is 100% secure. While we strive to use commercially acceptable means to protect your data, we cannot guarantee absolute security.`,
    },
    {
      title: "Your Rights",
      content: `You have the following rights regarding your personal data:

• **Access:** You can view the data we hold about you via your Profile page.
• **Correction:** You can update your name and profile picture at any time.
• **Deletion:** You can permanently delete your account and all associated data from the Settings page.
• **Data Portability:** Contact us if you need a copy of your data in a portable format.

To exercise any of these rights, please use the in-app settings or contact us at the email below.`,
    },
    {
      title: "Cookies",
      content: `NoSnore uses essential cookies to maintain your session and authentication state. We do not use third-party advertising cookies or tracking cookies. We use Vercel Analytics for anonymized, aggregate traffic analysis, which does not track individual users.`,
    },
    {
      title: "Changes to This Policy",
      content: `We may update this Privacy Policy from time to time. We will notify you of any significant changes by posting the new policy on this page with an updated effective date. Your continued use of the service after any changes constitutes your acceptance of the new policy.`,
    },
    {
      title: "Contact Us",
      content: `If you have any questions about this Privacy Policy, please contact us at:

support@nosnore.com`,
    },
  ];

  return (
    <div className="min-h-screen bg-black text-white">
      <Navbar />

      <main className="mx-auto max-w-3xl px-6 pt-32 pb-16">
        <div className="mb-12">
          <h1 className="text-4xl font-black tracking-tight text-white sm:text-5xl">
            Privacy{" "}
            <span className="bg-gradient-to-r from-blue-400 to-emerald-400 bg-clip-text text-transparent">
              Policy
            </span>
          </h1>
          <p className="mt-4 text-zinc-400">
            Effective Date: <span className="text-zinc-300">May 1, 2026</span>
          </p>
          <p className="mt-3 text-zinc-500 leading-relaxed">
            At <span className="font-semibold text-white">NoSnore</span>, your
            privacy is important to us. This policy explains what data we
            collect, how we use it, and your rights as a user.
          </p>
        </div>

        <div className="space-y-10">
          {sections.map((section, i) => (
            <div
              key={i}
              className="rounded-2xl border border-white/5 bg-zinc-900/40 p-8 backdrop-blur-sm"
            >
              <h2 className="mb-4 text-xl font-bold text-white">
                <span className="mr-3 text-blue-400">
                  {String(i + 1).padStart(2, "0")}.
                </span>
                {section.title}
              </h2>
              <div className="space-y-2">
                {section.content.split("\n").map((line, j) => (
                  <p
                    key={j}
                    className={`text-sm leading-relaxed ${
                      line.startsWith("•")
                        ? "text-zinc-400 pl-2"
                        : line.startsWith("support@")
                          ? "text-emerald-400 font-medium"
                          : "text-zinc-500"
                    }`}
                  >
                    {line.replace(/\*\*(.*?)\*\*/g, "$1")}
                  </p>
                ))}
              </div>
            </div>
          ))}
        </div>

        <div className="mt-16 flex justify-center">
          <Link
            href="/dashboard"
            className="group inline-flex items-center gap-2 rounded-2xl border border-white/10 bg-zinc-900 px-8 py-4 text-sm font-semibold text-white transition-all hover:border-emerald-500/30 hover:bg-zinc-800 hover:text-emerald-400"
          >
            <ArrowLeft className="h-4 w-4 transition-transform group-hover:-translate-x-1" />
            Back to Dashboard
          </Link>
        </div>
      </main>

      <Footer />
    </div>
  );
}
